### ISSUE TITLE
Crash trying to run app

### ISSUE THREAD

**Issue by CarlosJimenez** [egeorgiou/openCViOSFaceTrackingTutorial#1]
Hello
I am using a iPhone4S with IOS 5.0 and I am trying to run your example but I got the following: 

2013-05-29 22:36:04.615 openCViOSFaceTrackingTutorial[12448:707] deviceOrientationDidChange: 1
2013-05-29 22:36:04.619 openCViOSFaceTrackingTutorial[12448:707] rotate..
2013-05-29 22:36:04.622 openCViOSFaceTrackingTutorial[12448:707] layout preview layer
2013-05-29 22:36:04.624 openCViOSFaceTrackingTutorial[12448:707] camera available: YES
dyld: lazy symbol binding failed: Symbol not found: _objc_setProperty_nonatomic
  Referenced from: /var/mobile/Applications/945E8EF9-BC03-4430-9E34-5F7E53EF002E/openCViOSFaceTrackingTutorial.app/openCViOSFaceTrackingTutorial
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_setProperty_nonatomic
  Referenced from: /var/mobile/Applications/945E8EF9-BC03-4430-9E34-5F7E53EF002E/openCViOSFaceTrackingTutorial.app/openCViOSFaceTrackingTutorial
  Expected in: /usr/lib/libobjc.A.dylib

Could you help? Could be a problem with OpenVC (not compiled for ARM v6)?

NOTE: I compiled and runned in a iPhone 5 with IOS 6.1.4 and runs fine.

Thanks a lot. Your project is really nice.

**Comment by egeorgiou** [comment]
Sounds like a iOS version issue.

To be honest this is just example code, it’s not intended for production level use but rather as an example of how to use openCV.

Regards,

Evangelos Georgiou, BEng, MSc
PhD Student in the Centre for Robotic Research
[email]mailto:evangelos.georgiou@kcl.ac.uk[wordpress]http://www.mymobilerobots.com/[rss]http://mymobilerobots.com/myblog/feed/[linkedin]http://uk.linkedin.com/in/evangelosgeorgiou[google]https://plus.google.com/106813050218248819445[skype]http://myskype.info/egeorgiou[youtube]https://www.youtube.com/user/egeorgiou[twitter]https://twitter.com/egeorgiou

**Comment by bitm-cn** [comment]
Hi, Carlos, have you resolve the issue? I encounter the same, it will in mess if release one for iOS 5 and one for iOS 6...

**Comment by pradeepktg** [comment]
Hi @egeorgiou , Build was success , but i'm getting the below error when i run 

OpenCV Error: Null pointer (NULL or empty buffer) in cvOpenFileStorage, file /Users/vp/work/opencv/modules/core/src/persistence.cpp, line 2665
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/vp/work/opencv/modules/core/src/persistence.cpp:2665: error: (-27) NULL or empty buffer in function cvOpenFileStorage

Can you please help ?

**Comment by egeorgiou** [comment]
ios version?

**Comment by pradeepktg** [comment]
@egeorgiou Thanks for the reply. I fixed the issue by two things;
1. Added haarcascade file from some other site, which didn't work - i had removed it and added from your example
2. In prefix header - I just entered the file name without project name in prefix
